import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv("weather_data.csv")

df["datetime"] = pd.to_datetime(df["datetime"])
plt.figure(figsize=(10,5))
plt.plot(df["datetime"], df["temp"], marker="o")
plt.title("Temperature Trend")
plt.xlabel("Date Time")
plt.ylabel("Temperature (°C)")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize=(10,5))
plt.plot(df["datetime"], df["humidity"], marker="o")
plt.title("Humidity Trend")
plt.xlabel("Date Time")
plt.ylabel("Humidity (%)")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize=(10,5))
plt.plot(df["datetime"], df["pressure"], marker="o")
plt.title("Pressure Trend")
plt.xlabel("Date Time")
plt.ylabel("Pressure (hPa)")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize=(10,5))
plt.plot(df["datetime"], df["wind_speed"], marker="o")
plt.title("Wind Speed Trend")
plt.xlabel("Date Time")
plt.ylabel("Wind Speed (m/s)")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize=(10,5))
plt.plot(df["datetime"], df["clouds"], marker="o")
plt.title("Cloud Cover Trend")
plt.xlabel("Date Time")
plt.ylabel("Clouds (%)")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize=(10,5))
plt.plot(df["datetime"], df["visibility"], marker="o")
plt.title("Visibility Trend")
plt.xlabel("Date Time")
plt.ylabel("Visibility (meters)")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()